name: Node CI Ex

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Execute Hello World!
      uses: actions/hello-world-docker-action@v1

    - name: Install dependencies
      run: npm install

    - name: change modify permission for mocha
      run: chmod +x ./node_modules/.bin/mocha
      
    - name: Run tests
      run: npm test
